version: '3'
services:
  server27:
    container_name: myapp27
    restart: always
    build: ./server1
    expose:
      - '3001'
    environment:
      - MONGO_URI=mongodb://mongo27:27017/vrp27
      - PORT=3001
      - JWT_SECRET=jwtSecret
    volumes:
      - ./server1/upload:/usr/src/app/upload
    links:
      - mongo27

  nginx27:
    container_name: mynginx27
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./client/build:/usr/share/nginx/html
      - ./config:/etc/nginx/conf.d
    depends_on:
        - server27

  mongo27:
    container_name: mymongo27
    restart: always
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./mongo/mydb:/data/db
  